apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-api
  name: basket-api
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basket-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: basket-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: ConnectionString
              value: basket.data
            - name: ConnectionStrings__EventBus
              value: rabbitmq.leenet.svc.cluster.local
            - name: ConnectionStrings__Redis
              value: redis.leenet.svc.cluster.local
            - name: EventBusPassword
              value: 'guest'
            - name: EventBusUserName
              value: 'guest'
            - name: Identity__Url
              value: https://identity.leenet.link
            - name: OrchestratorType
            - name: UseLoadTest
              value: "False"
            - name: identityUrl
              value: http://identity-api
            - name: Kestrel__Endpoints__Http__Url
              value: http://0.0.0.0:80
            - name: Kestrel__Endpoints__gRPC__Url
              value: http://0.0.0.0:81
          image: master-0.local:32000/basket.api:1.0.118
          name: basket-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
