apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: basketdata
  name: basketdata
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basketdata
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: basketdata
    spec:
      containers:
        - image: redis:alpine
          name: basketdata
          resources: {}
      restartPolicy: Always
status: {}
