apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-api
  name: catalog-api
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: catalog-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: AzureStorageAccountKey
            - name: AzureStorageAccountName
            - name: AzureStorageEnabled
              value: "False"
            - name: ConnectionStrings__CatalogDb
              value: Server=sqldata.leenet.svc.cluster.local;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
            - name: ConnectionStrings__EventBus
              value: rabbitmq.leenet.svc.cluster.local
            - name: EventBusPassword
              value: 'guest'
            - name: EventBusUserName
              value: 'guest'
            - name: OrchestratorType
            - name: PicBaseUrl
            - name: UseCustomizationData
              value: "True"
            - name: Kestrel__Endpoints__Http__Url
              value: http://0.0.0.0:80
            - name: Kestrel__Endpoints__gRPC__Url
              value: http://0.0.0.0:81
            - name: PicBaseUrl
              value: https://agg.leenet.link/c/api/v1/catalog/items/[0]/pic/
          image: master-0.local:32000/catalog.api:1.0.117
          name: catalog-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
