apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["sleep", "infinity"]
      # Install curl using apk
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "apk update && apk add curl"]
