apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: mobileshoppingagg
  name: mobileshoppingagg
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mobileshoppingagg
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: mobileshoppingagg
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: urls__basket
              value: http://basket-api
            - name: urls__catalog
              value: http://catalog-api
            - name: urls__identity
              value: http://identity-api
            - name: urls__orders
              value: http://ordering-api
          image: master-0.local:32000/mobileshoppingagg:1.0.118
          name: mobileshoppingagg
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
