apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: ordering-api
  name: ordering-api
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: ordering-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: CheckUpdateTime
              value: "30000"
            - name: ConnectionStrings__OrderingDb
              value: Server=sqldata.{{ .Values.appNamespace }}.svc.cluster.local;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true
            - name: ConnectionStrings__EventBus
              value: rabbitmq.{{ .Values.appNamespace }}.svc.cluster.local
            - name: EventBusPassword
              value: 'guest'
            - name: EventBusUserName
              value: 'guest'
            - name: Identity__ExternalUrl
              value: https://identity.{{ .Values.rootDomainName }}
            - name: Identity__Url
              value: https://identity.{{ .Values.rootDomainName }}
            - name: Kestrel__Endpoints__Http__Url
              value: http://0.0.0.0:80
            - name: Kestrel__Endpoints__gRPC__Url
              value: http://0.0.0.0:81
            - name: OrchestratorType
            - name: UseCustomizationData
              value: "True"
            - name: UseLoadTest
              value: "False"
          image: {{ .Values.registry.url }}/ordering.api:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: ordering-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
