apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: ordering-signalrhub
  name: ordering-signalrhub
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering-signalrhub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: ordering-signalrhub
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__EventBus
              value: rabbitmq.leenet.svc.cluster.local
          image: master-0.local:32000/ordering.signalrhub:1.0.118
          name: ordering-signalrhub
          resources: {}
      restartPolicy: Always
status: {}
