apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-api
  name: payment-api
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: payment-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: ConnectionStrings__EventBus
              value: rabbitmq.{{ .Values.appNamespace }}.svc.cluster.local
            - name: EventBusPassword
              value: 'guest'
            - name: EventBusUserName
              value: 'guest'
            - name: OrchestratorType
          image: {{ .Values.registry.url }}/payment.api:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: payment-api
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
