apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: seq
    spec:
      containers:
        - image: datalust/seq:latest
          name: seq
          env:
            - name: ACCEPT_EULA
              value: "Y"
          resources: {}
      restartPolicy: Always
status: {}
