apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webshoppingagg
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - agg.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host:  webshoppingagg.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-apigwms
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - eshop.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /mobileshoppingagg
      route:
        - destination:
            host: mobileshoppingagg.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webhooks-web
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - eshop.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /webhooks-web
      route:
        - destination:
            host: webhooks-client.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webhooks-api
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - eshop.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /webhooks-api
      route:
        - destination:
            host: webhooks-api.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webstatus
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - eshop.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /webstatus
      route:
        - destination:
            host: webstatus.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 5107
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webspa
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - webspa.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webspa.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 5104
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-webmvc
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - eshop.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webmvc.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-identity
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - identity.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host:  identity-api.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eshop-ordering-signalrhub
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - signalr.{{ .Values.rootDomainName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host:  ordering-signalrhub.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 80