apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: webmvc
  name: webmvc
  namespace: {{ .Values.appNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webmvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: webmvc
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: BasketUrl
              value: http://basket-api
            - name: CatalogUrl
              value: http://catalog-api
            - name: IdentityUrl
              value: https://identity.{{ .Values.rootDomainName }}
            - name: Identity__ExternalUrl
              value: https://identity.{{ .Values.rootDomainName }}
            - name: CallBackUrl
              value: https://eshop.{{ .Values.rootDomainName }}
            - name: OrchestratorType
            - name: OrderingUrl
              value: http://ordering-api
            - name: PaymentUrl
              value: http://payment-api
            - name: PurchaseUrl
              value: https://agg.{{ .Values.rootDomainName }}
            - name: UseCustomizationData
              value: "True"
            - name: UseLoadTest
              value: "False"
            - name: SignalrHubUrl
              value: https://signalr.{{ .Values.rootDomainName }}
          image: {{ .Values.registry.url }}/webmvc:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: webmvc
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
