apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: webspa
  name: webspa
  namespace: leenet
spec:
  ports:
    - name: "5104"
      port: 5104
      targetPort: 80
  selector:
    io.kompose.service: webspa
status:
  loadBalancer: {}
