apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: webstatus
  name: webstatus
  namespace: leenet
spec:
  ports:
    - name: "5107"
      port: 5107
      targetPort: 80
  selector:
    io.kompose.service: webstatus
status:
  loadBalancer: {}
