apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: webshoppingagg
  name: webshoppingagg
  namespace: leenet
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: http2
      port: 81
      targetPort: 81
  selector:
    io.kompose.service: webshoppingagg
status:
  loadBalancer: {}
