apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: webstatus
  name: webstatus
  namespace: leenet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webstatus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.prod.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: webstatus
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: BasketUrl
              value: http://basket-api/hc
            - name: CatalogUrl
              value: http://catalog-api/hc
            - name: IdentityUrl
              value: http://identity-api/hc
            - name: OrchestratorType
            - name: OrderingUrl
              value: http://ordering-api/hc
            - name: PaymentUrl
              value: http://payment-api/hc
            - name: mvc
              value: http://webmvc/hc
            - name: spa
              value: http://webspa/hc
          image: master-0.local:32000/webstatus:1.0.118
          name: webstatus
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
